"""
generate_tables_EF.py — Phase D LaTeX table generation.

Appends Tables E and F to results/paper_tables.tex:
  Table E: Barrier benchmark (DPG vs MC at selected stock prices)
  Table F: Barrier monitoring frequency comparison

Usage:
  python3 scripts/generate_tables_EF.py
"""

import csv
import os

OUTPUT = "results/paper_tables_phaseD.tex"


def fmt(x, digits=4):
    """Format float with given significant digits."""
    try:
        v = float(x)
    except (ValueError, TypeError):
        return str(x)
    if abs(v) < 1e-14:
        return "0"
    return f"{v:.{digits}f}"


def fmt_sci(x, digits=2):
    try:
        v = float(x)
    except (ValueError, TypeError):
        return str(x)
    return f"{v:.{digits}e}"


# ---------------------------------------------------------------------------
# Table E: Barrier benchmark
# ---------------------------------------------------------------------------
def table_barrier_benchmark():
    path = "results/convergence/v5_barrier_benchmark.csv"
    if not os.path.exists(path):
        return "% Table E: v5_barrier_benchmark.csv not found\n"

    rows = []
    with open(path) as f:
        for line in f:
            if not line.startswith('#'):
                rows.append(line)
    reader = csv.DictReader(rows)
    data = list(reader)

    lines = []
    lines.append(r"\newcommand{\tableBarrierBenchmark}{%")
    lines.append(r"% Table E: Discrete double-barrier call — DPG vs Monte Carlo benchmark")
    lines.append(r"% T=0.5, r=0.1, sigma=0.2, K=100, S_L=95, S_U=125")
    lines.append(r"% DPG: primal H1(1), N_x=200, N_t=1000")
    lines.append(r"% MC:  1,000,000 paths, geometric Brownian motion, exact monitoring dates")
    lines.append(r"\begin{tabular}{c c r r r r}")
    lines.append(r"\hline")
    lines.append(r"$S$ & Monitoring & MC Price & DPG Price & Abs.\ Error & Rel.\ Error \\")
    lines.append(r"\hline")

    current_mon = None
    for row in data:
        mon = row.get("monitoring", "")
        if mon != current_mon:
            if current_mon is not None:
                lines.append(r"\hline")
            current_mon = mon
        S   = fmt(row["S"], 4)
        mc  = fmt(row["benchmark_value"], 4)
        dpg = fmt(row["DPG_price"], 4)
        ae  = fmt_sci(row["abs_error"], 1)
        re  = fmt_sci(row["rel_error"], 1)
        cap_mon = mon.capitalize() if mon else ""
        lines.append(f"{S} & {cap_mon} & {mc} & {dpg} & {ae} & {re} \\\\")

    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Table F: Monitoring frequency
# ---------------------------------------------------------------------------
def table_barrier_monitoring():
    path = "results/convergence/v5_barrier_monitoring_study.csv"
    if not os.path.exists(path):
        return "% Table F: v5_barrier_monitoring_study.csv not found\n"

    rows = []
    with open(path) as f:
        for line in f:
            if not line.startswith('#'):
                rows.append(line)
    reader = csv.DictReader(rows)
    data = list(reader)

    lines = []
    lines.append(r"\newcommand{\tableBarrierMonitoring}{%")
    lines.append(r"% Table F: Barrier price vs monitoring frequency (S_0=100)")
    lines.append(r"% T=0.5, r=0.1, sigma=0.2, K=100, S_L=95, S_U=125")
    lines.append(r"\begin{tabular}{l c r r r}")
    lines.append(r"\hline")
    lines.append(r"Monitoring & $N_{\rm dates}$ & Price at $S_0=100$ & "
                 r"European Price & Ratio \\")
    lines.append(r"\hline")

    for row in data:
        mon   = row.get("monitoring_type", "").capitalize()
        ndates = row.get("n_monitoring_dates", "0")
        price  = fmt(row["price_at_S0"], 4)
        eu     = fmt(row["european_price"], 4)
        ratio  = fmt(row["price_ratio_to_european"], 4)
        lines.append(f"{mon} & {ndates} & {price} & {eu} & {ratio} \\\\")

    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    tex_E = table_barrier_benchmark()
    tex_F = table_barrier_monitoring()

    # Write Phase D tables to paper_tables_phaseD.tex (separate from root-owned paper_tables.tex)
    header = (
        "% ================================================================\n"
        "% Phase D: Barrier option results (auto-generated by generate_tables_EF.py)\n"
        "% Include in main paper with \\input{results/paper_tables_phaseD.tex}\n"
        "% ================================================================\n\n"
    )

    with open(OUTPUT, "w") as f:
        f.write(header)
        f.write(tex_E)
        f.write("\n")
        f.write(tex_F)
        f.write("\n")

    print(f"Appended Tables E and F to {OUTPUT}")


if __name__ == "__main__":
    main()
